### ISSUE TITLE
메인페이지

### ISSUE THREAD

**Issue by syckor** [yejin0718/hanghaeB-B#2]
## Description

설명을 작성해주세요.

## Todo

- [ ] 전체 리스트 받아오기
- [ ] 지역별 리스트 받아오기
- [ ] 태그별 리스트 받아오기
- [ ] 검색 기능 

## Etc

기타사항
